# Generated by Django 5.0.2 on 2024-02-09 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0004_game_studio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game_collection', to=settings.AUTH_USER_MODEL, verbose_name='Author etogo kolleksiya')),
                ('games_list', models.ManyToManyField(blank=True, related_name='game_collection', to='games.game')),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_collection', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
