# Generated by Django 5.0.2 on 2024-02-07 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('workers_count', models.PositiveIntegerField()),
                ('games_count', models.IntegerField()),
            ],
        ),
    ]
