# Generated by Django 5.0.2 on 2024-02-08 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_genre_game_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='studio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='games.studio'),
        ),
    ]
