# Generated by Django 5.0.2 on 2024-02-11 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_game_studio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['id']},
        ),
    ]
