# Generated by Django 5.0.2 on 2024-02-11 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_alter_game_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='games.genre'),
        ),
        migrations.AlterField(
            model_name='game',
            name='studio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='games.studio'),
        ),
        migrations.AlterField(
            model_name='game',
            name='year',
            field=models.IntegerField(),
        ),
    ]
